//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City_tbl
    {
        public int CityID { get; set; }
        public Nullable<int> StateID { get; set; }
        public string City { get; set; }
    
        public virtual State_tbl State_tbl { get; set; }
    }
}
